Version Check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,6 +63,7 @@ jobs:
           DEV_VERSION=$(./gradlew -q currentVersion)
           cd ..
           echo "DEV_VERSION=$DEV_VERSION"
+          rm -rf dev-branch
           
           #MAIN-Version
           git clone --depth 1 --branch main "$REPO_URL" main-branch
@@ -70,7 +71,58 @@ jobs:
           MAIN_VERSION=$(./gradlew -q currentVersion)
           cd ..
           echo "MAIN_VERSION=$MAIN_VERSION"
+          rm -rf main-branch
+
+      - name: Version Check
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
+          echo "BASE_BRANCH=$BASE_BRANCH"
           
+          PR_VERSION="${{ env.PR_VERSION }}"
+          DEV_VERSION="${{ env.DEV_VERSION }}"
+          MAIN_VERSION="${{ env.MAIN_VERSION }}"
+          
+          echo "PR_VERSION=$PR_VERSION"
+          echo "DEV_VERSION=$DEV_VERSION"
+          echo "MAIN_VERSION=$MAIN_VERSION"
+          
+          if [ "$BASE_BRANCH" = "dev" ]; then
+            echo "PR into dev => applying dev rules"
+            if [ "$DEV_VERSION" = "$PR_VERSION" ]; then
+              echo "OK: dev version == PR version (no bump needed)"
+              exit 0
+            else
+              # if dev == main and PR > dev => bump dev
+              if [ "$MAIN_VERSION" = "$DEV_VERSION" ]; then
+                if [[ "$PR_VERSION" > "$DEV_VERSION" ]]; then
+                  echo "Bumping dev"
+                  gradlew incrementMinor
+                  exit 0
+                else
+                  echo "FAIL: dev == main, but PR version is NOT greater than dev."
+                  exit 1
+                fi
+              else
+                echo "FAIL: dev != PR version, and dev != main."
+                exit 1
+              fi
+            fi
+
+          elif [ "$BASE_BRANCH" = "main" ]; then
+            echo "PR into main => PR version must be > main"
+            if [[ "$PR_VERSION" > "$MAIN_VERSION" ]]; then
+              echo "OK: PR version is greater than main version"
+              exit 0
+            else
+              echo "FAIL: PR version is NOT greater than main version"
+              exit 1
+            fi
+
+          else
+            echo "Base branch is '$BASE_BRANCH'; version check skipped"
+            exit 0
+          fi
 
       - name: Setup Java
         uses: actions/setup-java@v4
