debug path

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,8 +61,12 @@ jobs:
           ./gradlew reportScoverage
           ls -la build/reports/scoverage/
 
-      - name: Find scov
-        run: find . -name "scoverage.xml"
+      - name: Check if scoverage.xml Exists
+        run: |
+          if [ ! -f (pwd)/build/reports/scoverage/scoverage.xml ]; then
+            echo "Coverage report not found at build/reports/scoverage/scoverage.xml"
+            exit 1
+          fi
 
       - name: Build Scala-Docs
         run: |
@@ -81,7 +85,7 @@ jobs:
           -Dsonar.tests=src/test/resources,src/test/scala,src/test/groovy \
           -Dsonar.junit.reportPaths=build/test-results/test \
           -Dsonar.scala.scapegoat.reportPaths=build/reports/scapegoat/src/scapegoat-scalastyle.xml,build/reports/scapegoat/testsrc/scapegoat-scalastyle.xml \
-          -Dsonar.scala.coverage.reportPaths=./build/reports/scoverage/scoverage.xml \
+          -Dsonar.scala.coverage.reportPaths=(pwd)/build/reports/scoverage/scoverage.xml \
           -Dsonar.groovy.binaries=build/classes/groovy \
           -Dsonar.exclusions=src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
         env:
