Added check for naming convention

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,6 +25,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check branch naming convention
+        if: startsWith(github.ref, 'refs/heads/')
+        run: |
+          branch_name="${GITHUB_REF#refs/heads/}"
+          if [[ ! "$branch_name" =~ ^[\\p{Ll}]{2}/#\\d+.* ]]; then
+            echo "Error: Branch name must start with two lowercase initials (e.g., ps/#1337-FeatureName)."
+            exit 1
+          fi
+
       - name: Checkout Source
         uses: actions/checkout@v4
         with:
