final

diff --git a/.github/workflows/dependabot-auto-merge.yml b/.github/workflows/dependabot-auto-merge.yml
--- a/.github/workflows/dependabot-auto-merge.yml
+++ b/.github/workflows/dependabot-auto-merge.yml
@@ -1,8 +1,5 @@
 name: Dependabot auto-merge
-on:
-  workflow_run:
-    workflows: [ "Dependabot auto-approve" ]
-    types: [ completed ]
+on: pull_request
 
 permissions:
   contents: write
@@ -18,6 +15,19 @@ jobs:
         uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
         with:
           github-token: "${{ secrets.GITHUB_TOKEN }}"
+
+      - name: Check Snapshot
+        if: contains(steps.metadata.outputs.new-version, 'snap')
+        run: |
+          echo "::error::Snapshot versions are not allowed – workflow stopped."
+          exit 1 
+
+      - name: Approve the PR
+        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
+        run: gh pr review --approve "$PR_URL"
+        env:
+          PR_URL: ${{github.event.pull_request.html_url}}
+          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
       - name: Enable auto-merge for Dependabot PRs
         if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
