update

diff --git a/.github/workflows/dependabot-review.yml b/.github/workflows/dependabot-review.yml
--- a/.github/workflows/dependabot-review.yml
+++ b/.github/workflows/dependabot-review.yml
@@ -15,8 +15,14 @@ jobs:
         with:
           github-token: "${{ secrets.GITHUB_TOKEN }}"
 
+      - name: Check Snapshot
+        if: contains(steps.metadata.outputs.new-version, 'snap')
+        run: |
+          echo "::error::Snapshot versions are not allowed – workflow stopped."
+          exit 1 
+
       - name: Approve the PR
-        if: ${{ !contains(steps.metadata.outputs.new-version, 'snap') }}
+        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
         run: gh pr review --approve "$PR_URL"
         env:
           PR_URL: ${{github.event.pull_request.html_url}}
